name: Release

on:
  push:
    branches:
      - main


permissions:
    contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
        contents: write
        issues: write
        pull-requests: write
        id-token: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: 'pnpm'

      - name: Verify integrity
        run: pnpm audit --prod

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
